yarn install
lerna clean
cd packages/core
yarn build
lerna link
cd ../../packages/lib-react
yarn build
lerna link
cd ../../packages/ext-identity
yarn build
lerna link
cd ../../packages/ext-groups
yarn build
lerna link
cd ../../packages/ext-doc-signature
yarn build
lerna link
cd ../..
lerna bootstrap
