yarn install
lerna clean
cd packages/core
yarn build
lerna link
yarn link
cd ../../packages/comm
yarn build
lerna link
yarn link
cd ../../packages/lib-node
yarn build
lerna link
yarn link
cd ../../packages/lib-react
yarn build
lerna link
yarn link
cd ../../packages/ext-comm
yarn build
lerna link
yarn link
cd ../../packages/ext-auth
yarn build
lerna link
yarn link
cd ../../packages/ext-identity
yarn build
lerna link
yarn link
cd ../../packages/ext-groups
yarn build
lerna link
yarn link
cd ../../packages/ext-doc-signature
yarn build
lerna link
yarn link
cd ../..
lerna bootstrap
