yarn install
lerna clean
cd packages/common
yarn build
lerna link
cd ../../packages/did
yarn build
lerna link
cd ../../packages/core
yarn build
lerna link
cd ../../packages/extension
yarn build
lerna link
cd ../../packages/lib-react
yarn build
lerna link
cd ../../packages/mold-wallet-web
yarn build
lerna link
cd ../../packages/ext-identity
yarn build
lerna link
cd ../../packages/ext-identity-web
yarn build
lerna link
cd ../../packages/ext-groups
yarn build
lerna link
cd ../../packages/ext-groups-web
yarn build
lerna link
cd ../../packages/ext-doc-signature
yarn build
lerna link
cd ../..
lerna bootstrap
