
export const ERROR_NO_SERVER_CLIENT = 'ERROR_NO_SERVER_CLIENT'

export const ERROR_NO_WALLET_HANDLER_AUTH = 'ERROR_NO_WALLET_HANDLER_AUTH'

export const ERROR_NO_EXTENSION_REGISTRY = 'ERROR_NO_EXTENSION_REGISTRY'