
export const ERROR_WIDGET_AUTHENTICATION = 'ERROR_WIDGET_AUTHENTICATION'
export const ERROR_WIDGET_EXTENSION = 'ERROR_WIDGET_EXTENSION'
export const ERROR_CREATION_READYTO_SIGN = 'ERROR_CREATION_READYTO_SIGN'