
export const ERROR_CREATION_AUTHENTICATION = 'ERROR_CREATION_AUTHENTICATION'
export const ERROR_CREATION_EXTENSION = 'ERROR_CREATION_EXTENSION'
export const ERROR_CREATION_READYTO_SIGN = 'ERROR_CREATION_READYTO_SIGN'